//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersOrder
    {
        public int CustomerOrderId { get; set; }
        public int CustomerId { get; set; }
        public int OrderId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
    }
}
